⭐ Train an LSTM to solve the XOR problem: that is, given a sequence of bits, determine its parity. The LSTM should consume the sequence, one bit at a time, and then output the correct answer at the sequence’s end. Test the two approaches below:

- Generate a dataset of random 100,000 binary strings of length 50. Train the LSTM; what performance do you get?

- Generate a dataset of random 100,000 binary strings, where the length of each string is independently and randomly chosen between 1 and 50. Train the LSTM. Does it succeed? What explains the difference?

In [1]:
# import dependencies

import torch
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline  

from utils.data import generate_data, generate_rand_data
from network.network import Network


In [2]:
# generate data and initialize model
bit_strings, pairities = generate_data(10, 2)
model = Network(in_dim=1, out_dim=1, hid_dim=10, num_lay=1, lr=0.01)
print(pairities.shape)
print(bit_strings.shape)

(10, 1)
(10, 2)


In [3]:
# train network
model.optimize(bit_strings, pairities, 2, 5)

torch.Size([10, 1])

tensor([0., 0., 0.])
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])
ACC:  tensor(0.)
tensor([[[1.],
         [0.],
         [1.],
         [0.],
         [1.],
         [0.],
         [1.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [1.],
         [0.]]])
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.]])


Training Network: 100%|███████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 17.23it/s]


torch.Size([10, 1])
torch.Size([10, 1])
tensor(0.7000)


In [ ]:
# plot loss
plt.plot(model.historical_loss, label="Loss")
plt.plot(model.historical_accuracy, label="Accuracy")
plt.legend()
plt.show()